from __future__ import annotations
from typing import Optional
from server_modules.connectors.autopilot_connector_config import (
    _AUTOPILOT_ERROR_CATEGORY_HINTS,
    _AUTOPILOT_EVENT_DEDUP,
    _AUTOPILOT_EVENT_DEDUP_LOCK,
    _AUTOPILOT_NON_RETRYABLE_RUN_ERROR_HINTS,
    _CHANNEL_DEAD_LETTER_LOCK,
    _TELEGRAM_MENU_GOAL_TEMPLATES,
    _TELEGRAM_QUICK_GOAL_TEMPLATES,
    _resolve_state_dir,
    _resolve_state_file,
    _telegram_get_updates_process_lock,
    DEFAULT_CHAT_PREFIX,
    EMPYRALIS_STATE_HOME,
    EMPYRALIST_RUNTIME_URL,
    EMPYRALIST_WEB_URL,
    EMPYRALIST_WORKFLOW_API_URL,
    ORION_CHANNEL_DEAD_LETTER_FILE,
    ORION_CHANNEL_DEAD_LETTER_LIMIT,
    ORION_LOCAL_LEASE_SECONDS,
    ORION_TELEGRAM_AUTOPILOT_MAX_UPDATES,
    ORION_TELEGRAM_AUTOPILOT_POLL_SECONDS,
    ORION_TELEGRAM_AUTOPILOT_SHOW_BUTTONS,
    ORION_TELEGRAM_AUTOPILOT_STATE_FILE,
    ORION_TELEGRAM_CAMERA_SETUP_STATE_FILE,
    ORION_TELEGRAM_GUIDED_AUTOMATION_SETUP_ENABLED,
    ORION_TELEGRAM_INSTALLED_SKILLS_ENABLED,
    ORION_TELEGRAM_MEDIA_DIR,
    ORION_TELEGRAM_MEDIA_ENABLED,
    ORION_TELEGRAM_MEDIA_INCLUDE_IN_GOAL,
    ORION_TELEGRAM_MEDIA_MAX_BYTES,
    ORION_TELEGRAM_MEDIA_MAX_ITEMS,
    ORION_TELEGRAM_ONBOARDING_ENABLED,
    ORION_TELEGRAM_ONBOARDING_STATE_FILE,
    ORION_TELEGRAM_PROFILE_STATE_FILE,
    ORION_TELEGRAM_SPACE_STATUS_ENABLED,
    ORION_WHATSAPP_AUTOPILOT_STATE_FILE,
    PROJECT_ROOT,
)
from server_modules.connectors.autopilot_connector_export_facade import AutopilotConnectorExportFacade
from server_modules.connectors.autopilot_connector_shell_builder import build_autopilot_connector_shell_service
from server_modules.connectors.autopilot_connector_shell_service import AutopilotConnectorShellService
_server = None
_SYNC_SERVER_GLOBALS = (
    "TELEGRAM_AUTOPILOT_THREAD",
    "TELEGRAM_AUTOPILOT_STATE",
    "WHATSAPP_AUTOPILOT_STATE",
)
_AUTOPILOT_CONNECTOR_SHELL_SERVICE: Optional[AutopilotConnectorShellService] = None


def _autopilot_connector_shell_service() -> AutopilotConnectorShellService:
    global _AUTOPILOT_CONNECTOR_SHELL_SERVICE
    if _AUTOPILOT_CONNECTOR_SHELL_SERVICE is None:
        _AUTOPILOT_CONNECTOR_SHELL_SERVICE = build_autopilot_connector_shell_service(
            global_namespace=globals(),
            sync_server_globals=_SYNC_SERVER_GLOBALS,
            server_getter=lambda: _server,
            server_setter=lambda value: globals().__setitem__("_server", value),
            import_server=lambda: __import__("server", fromlist=["*"]),
        )
    return _AUTOPILOT_CONNECTOR_SHELL_SERVICE

_AUTOPILOT_EXPORT_FACADE = AutopilotConnectorExportFacade(global_namespace=globals())

_autopilot_channel_registry_bridge_service = _AUTOPILOT_EXPORT_FACADE.autopilot_channel_registry_bridge_service
_telegram_service_registry = _AUTOPILOT_EXPORT_FACADE.telegram_service_registry
_telegram_helper_registry_bridge_service = _AUTOPILOT_EXPORT_FACADE.telegram_helper_registry_bridge_service
_telegram_helper_registry = _AUTOPILOT_EXPORT_FACADE.telegram_helper_registry
_telegram_run_dispatch_service = _AUTOPILOT_EXPORT_FACADE.telegram_run_dispatch_service
_autopilot_support_service_registry = _AUTOPILOT_EXPORT_FACADE.autopilot_support_service_registry
_autopilot_runtime_service_registry = _AUTOPILOT_EXPORT_FACADE.autopilot_runtime_service_registry
_autopilot_shared_service_registry = _AUTOPILOT_EXPORT_FACADE.autopilot_shared_service_registry
_autopilot_status_service = _AUTOPILOT_EXPORT_FACADE.autopilot_status_service
_autopilot_endpoint_service = _AUTOPILOT_EXPORT_FACADE.autopilot_endpoint_service
_autopilot_event_service = _AUTOPILOT_EXPORT_FACADE.autopilot_event_service
_whatsapp_service_registry = _AUTOPILOT_EXPORT_FACADE.whatsapp_service_registry
_autopilot_profile_service = _AUTOPILOT_EXPORT_FACADE.autopilot_profile_service
_telegram_connector_support_service = _AUTOPILOT_EXPORT_FACADE.telegram_connector_support_service
_runtime_status_service = _AUTOPILOT_EXPORT_FACADE.runtime_status_service
_autopilot_workflow_setup_service = _AUTOPILOT_EXPORT_FACADE.autopilot_workflow_setup_service
_telegram_connector_context_service = _AUTOPILOT_EXPORT_FACADE.telegram_connector_context_service
_autopilot_approval_service = _AUTOPILOT_EXPORT_FACADE.autopilot_approval_service
_telegram_transport_service = _AUTOPILOT_EXPORT_FACADE.telegram_transport_service
_telegram_terminal_service = _AUTOPILOT_EXPORT_FACADE.telegram_terminal_service
_autopilot_common_support_service = _AUTOPILOT_EXPORT_FACADE.autopilot_common_support_service
_autopilot_run_entry_service = _AUTOPILOT_EXPORT_FACADE.autopilot_run_entry_service
_autopilot_runtime_support_service = _AUTOPILOT_EXPORT_FACADE.autopilot_runtime_support_service
_autopilot_skill_service = _AUTOPILOT_EXPORT_FACADE.autopilot_skill_service
_autopilot_channel_support_service = _AUTOPILOT_EXPORT_FACADE.autopilot_channel_support_service
_autopilot_event_bridge_service = _AUTOPILOT_EXPORT_FACADE.autopilot_event_bridge_service
_autopilot_terminal_bridge_service = _AUTOPILOT_EXPORT_FACADE.autopilot_terminal_bridge_service
_autopilot_state_bridge_service = _AUTOPILOT_EXPORT_FACADE.autopilot_state_bridge_service
_telegram_compatibility_bridge_service = _AUTOPILOT_EXPORT_FACADE.telegram_compatibility_bridge_service
_whatsapp_webhook_bridge_service = _AUTOPILOT_EXPORT_FACADE.whatsapp_webhook_bridge_service
_load_telegram_autopilot_state = _AUTOPILOT_EXPORT_FACADE.load_telegram_autopilot_state
_load_whatsapp_autopilot_state = _AUTOPILOT_EXPORT_FACADE.load_whatsapp_autopilot_state
_telegram_autopilot_snapshot = _AUTOPILOT_EXPORT_FACADE.telegram_autopilot_snapshot
_whatsapp_autopilot_snapshot = _AUTOPILOT_EXPORT_FACADE.whatsapp_autopilot_snapshot
_whatsapp_autopilot_activate = _AUTOPILOT_EXPORT_FACADE.whatsapp_autopilot_activate
_telegram_increment_processed_updates = _AUTOPILOT_EXPORT_FACADE.telegram_increment_processed_updates
_telegram_set_connectors_seen = _AUTOPILOT_EXPORT_FACADE.telegram_set_connectors_seen
_mark_telegram_autopilot_started = _AUTOPILOT_EXPORT_FACADE.mark_telegram_autopilot_started
_init = _AUTOPILOT_EXPORT_FACADE.init_runtime
_record_channel_event = _AUTOPILOT_EXPORT_FACADE.record_channel_event
_append_channel_dead_letter = _AUTOPILOT_EXPORT_FACADE.append_channel_dead_letter
_record_channel_event_throttled = _AUTOPILOT_EXPORT_FACADE.record_channel_event_throttled
_telegram_menu_service = _AUTOPILOT_EXPORT_FACADE.telegram_menu_service
_telegram_safe_path_token = _AUTOPILOT_EXPORT_FACADE.telegram_safe_path_token
_telegram_build_goal_with_profile = _AUTOPILOT_EXPORT_FACADE.telegram_build_goal_with_profile
_telegram_workspace_connector_context = _AUTOPILOT_EXPORT_FACADE.telegram_workspace_connector_context
_telegram_extract_message = _AUTOPILOT_EXPORT_FACADE.telegram_extract_message
_telegram_build_goal_with_attachments = _AUTOPILOT_EXPORT_FACADE.telegram_build_goal_with_attachments
_telegram_route_message = _AUTOPILOT_EXPORT_FACADE.telegram_route_message
handle_telegram_send_message = _AUTOPILOT_EXPORT_FACADE.handle_telegram_send_message
handle_telegram_autopilot_test_message = _AUTOPILOT_EXPORT_FACADE.handle_telegram_autopilot_test_message
handle_whatsapp_twilio_webhook = _AUTOPILOT_EXPORT_FACADE.handle_whatsapp_twilio_webhook
_run_telegram_autopilot_forever = _AUTOPILOT_EXPORT_FACADE.run_telegram_autopilot_forever
handle_telegram_autopilot_status = _AUTOPILOT_EXPORT_FACADE.handle_telegram_autopilot_status
handle_whatsapp_autopilot_status = _AUTOPILOT_EXPORT_FACADE.handle_whatsapp_autopilot_status
handle_list_autopilot_profiles = _AUTOPILOT_EXPORT_FACADE.handle_list_autopilot_profiles
