from fastapi import APIRouter, Depends

from server_modules.runtime_common import require_api_key
from server_modules import connectors_core as core

router = APIRouter()

router.add_api_route("/providers/profiles", core.list_provider_profiles, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/profiles", core.upsert_provider_profile, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/profiles/{profile_id}/enable", core.enable_provider_profile, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/profiles/{profile_id}/disable", core.disable_provider_profile, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/profiles/{profile_id}", core.delete_provider_profile, methods=['DELETE'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/profiles/health", core.provider_profiles_health, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/tools/contracts", core.get_tool_contracts, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/tools/policy/evaluate", core.evaluate_tools_policy, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers", core.list_providers, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/anthropic/local-cli/status", core.get_anthropic_local_cli_status, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/anthropic/local-cli/login", core.start_anthropic_local_cli_login, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/test", core.test_provider_credentials, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/providers/{provider}/models", core.get_provider_models, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/credentials/vault", core.list_credentials_vault, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors", core.list_connectors, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault", core.list_connectors_vault, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault/{connector_id}/microsoft-drive", core.browse_microsoft_connector_drive, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault/{connector_id}/google-drive", core.browse_google_connector_drive, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault/{connector_id}/google-doc", core.create_google_connector_document, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault/{connector_id}/google-sheet", core.create_google_connector_spreadsheet, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/channels/whatsapp/twilio/webhook", core.whatsapp_twilio_webhook, methods=['POST'])
router.add_api_route("/channels/telegram/autopilot/status", core.telegram_autopilot_status, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/channels/whatsapp/autopilot/status", core.whatsapp_autopilot_status, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/channels/autopilot/profiles", core.list_autopilot_profiles, methods=['GET'], dependencies=[Depends(require_api_key)])
router.add_api_route("/channels/telegram/send", core.telegram_send_message, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/channels/telegram/autopilot/test-message", core.telegram_autopilot_test_message, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault", core.create_connector_vault, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault/{credential_id}", core.update_connector_vault, methods=['PATCH'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault/{credential_id}/test", core.test_connector_vault, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/connectors/vault/{credential_id}", core.delete_connector_vault, methods=['DELETE'], dependencies=[Depends(require_api_key)])
router.add_api_route("/credentials/vault", core.create_vault_credential, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/credentials/vault/{credential_id}", core.delete_vault_credential, methods=['DELETE'], dependencies=[Depends(require_api_key)])
router.add_api_route("/credentials/vault/{credential_id}/test", core.test_vault_credential, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/credentials/vault/rotate-key", core.rotate_vault_key, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/credentials/vault/export", core.export_vault_credentials, methods=['POST'], dependencies=[Depends(require_api_key)])
router.add_api_route("/credentials/vault/import", core.import_vault_credentials, methods=['POST'], dependencies=[Depends(require_api_key)])
